spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client-dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
my-name: hss01
---
server:
  port: 8203
spring:
  profiles: test
  application:
    name: microservicecloud-config-client-test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
my-name: hss05