spring:
  profiles:
    active:
    - dev
---
server:
  port: 7001 #注册中心占用7001端口
spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client

eureka:
  instance:
    #eureka服务端的实例名称
    hostname: 127.0.0.1
  client:
    #false不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
server:
  port: 7001 #注册中心占用7001端口
server:
  porfiles: test
  application:
    name: microservicecloud-config-eureka-client

eureka:
  instance:
    #eureka服务端的实例名称
    hostname: 127.0.0.1
  client:
    #false不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
